import { Router, type IRouter } from "express";
import { sql } from "drizzle-orm";
import { db, siteSettingsTable } from "@workspace/db";
import { requireAdmin } from "../lib/auth";
import { z } from "zod";

const router: IRouter = Router();

/* =============================================================
 * CONTENT SCHEMA
 * Single source of truth for the entire landing page CMS.
 * Every text/image you can edit from the admin panel is below.
 * Field types: "text" | "longtext" | "url" | "image"
 * =========================================================== */

export type FieldType = "text" | "longtext" | "url" | "image";
export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  default: string;
  hint?: string;
}
export interface SectionDef {
  key: string;
  label: string;
  description?: string;
  fields: FieldDef[];
}

const txt = (key: string, label: string, def: string, hint?: string): FieldDef => ({
  key, label, type: "text", default: def, hint,
});
const long = (key: string, label: string, def: string, hint?: string): FieldDef => ({
  key, label, type: "longtext", default: def, hint,
});
const url = (key: string, label: string, def: string, hint?: string): FieldDef => ({
  key, label, type: "url", default: def, hint,
});
const img = (key: string, label: string, def: string, hint?: string): FieldDef => ({
  key, label, type: "image", default: def, hint,
});

export const CONTENT_SCHEMA: SectionDef[] = [
  {
    key: "hero",
    label: "الواجهة الرئيسية (Hero)",
    description: "أوّل ما يراه الزائر — العنوان الكبير والصور المتعاقبة في الخلفيّة.",
    fields: [
      txt("eyebrow", "الكتابة العلوية", "حاضنة الأعمال والمجتمع التقني الرائد في قطاع غزة"),
      txt("eyebrowEn", "الكتابة العلوية (إنجليزي)", "Gaza's leading tech incubator & startup community"),
      txt("title1", "السطر الأول من العنوان", "نَحضن أحلامك،"),
      txt("title2", "السطر الثاني من العنوان (مُلوّن)", "في قلب غزّة."),
      txt("titlePrefix", "العنوان — البداية", "نَحضن"),
      txt("titlePrefixEn", "العنوان — البداية (إنجليزي)", "We grow Gaza's"),
      txt("rotatingWords", "الكلمات المتبدّلة (تُفصل بفواصل)", "مشاريعك,أحلامك,مستقبلك,طاقاتك"),
      txt("rotatingWordsEn", "الكلمات المتبدّلة (إنجليزي)", "ventures,dreams,futures,talent"),
      txt("titleSuffix", "العنوان — النهاية", "في قلب غزّة."),
      txt("titleSuffixEn", "العنوان — النهاية (إنجليزي)", "for the world."),
      long("subtitle", "النص الفرعي", "حاضنة أعمال ومجتمع تقني تأسّست من قلب قطاع غزة. نجسر الفجوة بين المواهب الغزية والعالم — بمساحات عمل احترافية، تدريب مكثّف، أرصدة سحابية، وحلول استقبال المدفوعات الدولية."),
      long("subtitleEn", "النص الفرعي (إنجليزي)", "Gaza's business incubator. We take your idea from paper to product, and from product to market — through mentorship, incubation programs, and a global network of experts and partners."),
      txt("ctaPrimary", "نص الزر الأساسي", "قدّم على الحاضنة"),
      url("ctaPrimaryHref", "رابط الزر الأساسي", "/apply"),
      txt("ctaSecondary", "نص الزر الثانوي", "تحدّث معنا"),
      url("ctaSecondaryHref", "رابط الزر الثانوي (واتساب)", "https://wa.me/970599000000"),
      txt("topRight", "كتابة أعلى يمين الشاشة", "Season · 2026 · open"),
      txt("onAirLabel", "شارة \"On Air\" أعلى يسار الشاشة", "On Air · غزّة"),
      txt("greetingMorning", "تحيّة الصباح (٥–١١)", "صباح الخير"),
      txt("greetingNoon", "تحيّة الظهيرة (١٢–١٦)", "نهارك مُبارك"),
      txt("greetingEvening", "تحيّة المساء (١٧–١٩)", "مساء النّور"),
      txt("greetingNight", "تحيّة الليل (٢٠–٤)", "ليلة هانئة"),
      txt("bookCtaLabel", "زرّ الحجز — التسمية", "احجز مقعدك"),
      txt("scrollLabel", "نصّ مؤشّر التمرير أسفل الشاشة", "Scroll"),
      txt("scrollLabelEn", "نصّ مؤشّر التمرير (إنجليزي)", "Scroll"),
      txt("verifyChip", "شارة \"موقّع · تحقّق\"", "موقّع · تحقّق"),
      txt("verifyChipEn", "شارة \"موقّع · تحقّق\" (إنجليزي)", "Signed · verify"),
      txt("estLabel", "نص الـ Est تحت الشعار", "Est · 2024"),
      txt("placeLabel", "نص الموقع تحت الشعار", "فلسطين · Gaza"),
      txt("stat1Value", "إحصائية ١ — الرقم", ""),
      txt("stat1Label", "إحصائية ١ — التسمية", "مقعد"),
      txt("stat1LabelEn", "إحصائية ١ — التسمية (إنجليزي)", "seats"),
      txt("stat2Value", "إحصائية ٢ — الرقم", ""),
      txt("stat2ValueEn", "إحصائية ٢ — الرقم (إنجليزي)", ""),
      txt("stat2Label", "إحصائية ٢ — التسمية", "منتسب"),
      txt("stat2LabelEn", "إحصائية ٢ — التسمية (إنجليزي)", "members"),
      txt("stat3Value", "إحصائية ٣ — الرقم", "١٠٠٪"),
      txt("stat3ValueEn", "إحصائية ٣ — الرقم (إنجليزي)", "100%"),
      txt("stat3Label", "إحصائية ٣ — التسمية", "مجّانيّ"),
      txt("stat3LabelEn", "إحصائية ٣ — التسمية (إنجليزي)", "free"),
      img("image1", "صورة الخلفية ١", "/photos/IMG_8357.webp"),
      img("image2", "صورة الخلفية ٢", "/photos/IMG_8347.webp"),
      img("image3", "صورة الخلفية ٣", "/photos/IMG_8358.webp"),
      img("image4", "صورة الخلفية ٤", "/photos/IMG_8341.webp"),
      img("image5", "صورة الخلفية ٥", "/photos/IMG_8352.webp"),
      img("image6", "صورة الخلفية ٦", "/photos/IMG_8300.webp"),
    ],
  },
  {
    key: "programs",
    label: "البرامج والفعاليّات",
    fields: [
      txt("label", "Eyebrow", "الفعاليّات والبرامج"),
      txt("titleA", "العنوان — الجزء الأول", "المكان يتنفّس بأهله،"),
      txt("titleAccent", "العنوان — كلمة مُلوّنة", "لا بجدرانه."),
      long("sub", "النص الفرعي", "إلى جانب المساحة المفتوحة يوميّاً، يُنظَّم Island Haven ورشاً تدريبيّة تطبيقيّة ومبادرات داخليّة، بعضها يقوده الفريق، وبعضها يقوده المنتسبون أنفسهم."),
      img("featureImage", "صورة الفعالية الرئيسية", "/photos/IMG_8352.webp"),
      txt("featureBadge", "شارة الصورة", "فعاليّة قادمة"),
      txt("featureEyebrow", "Eyebrow", "Made in Island Haven"),
      txt("featureTitle", "عنوان الفعالية الرئيسية", "صُنع في آيلاند هيفن."),
      long("featureBody", "نص الفعالية الرئيسية", "فعاليّة جديدة نطلقها قريباً، نفتح فيها الباب أمام منتسبي المجتمع لاقتراح ما يريدون أن يصنعوه داخل المساحة. كلّ فكرة تُبنى من أصحابها، وتُنفَّذ معهم — لأنّ المكان يصير أجمل حين يصنعه أهله."),
      txt("chipsLabel", "تسمية المربعات", "نرحّب باقتراحاتكم في"),
      txt("chip1Ar", "مربع ١ — عربي", "مواقع"),
      txt("chip1En", "مربع ١ — إنجليزي", "Sites"),
      txt("chip2Ar", "مربع ٢ — عربي", "أدوات"),
      txt("chip2En", "مربع ٢ — إنجليزي", "Tools"),
      txt("chip3Ar", "مربع ٣ — عربي", "تطويرات"),
      txt("chip3En", "مربع ٣ — إنجليزي", "Upgrades"),
      txt("chip4Ar", "مربع ٤ — عربي", "تحسينات"),
      txt("chip4En", "مربع ٤ — إنجليزي", "Improvements"),
      txt("featureCta", "نص الزر", "شاركنا فكرتك"),
      url("featureCtaHref", "رابط الزر", "https://www.instagram.com/ih_haven"),
      txt("sec1Ar", "بطاقة ١ — العنوان عربي", "ورش تدريبيّة دوريّة"),
      txt("sec1En", "بطاقة ١ — Eyebrow", "Weekly workshops"),
      long("sec1Body", "بطاقة ١ — النص", "برامج عمليّة في مهارات سوق العمل، يقدّمها الفريق ومتطوّعون من المجتمع، مفتوحة للمنتسبين وغير المنتسبين على حدّ سواء."),
      txt("sec2Ar", "بطاقة ٢ — العنوان عربي", "جلسات تشبيك ولقاءات مهنيّة"),
      txt("sec2En", "بطاقة ٢ — Eyebrow", "Networking nights"),
      long("sec2Body", "بطاقة ٢ — النص", "لقاءات شهريّة تجمع المستقلّين والخرّيجين والطلبة لتبادل الخبرات، وعرض مشاريع، وفتح أبواب التعاون بين أعضاء المجتمع."),
    ],
  },
  {
    key: "story",
    label: "قصّتنا (Story)",
    fields: [
      txt("label", "Eyebrow", "قصّتنا"),
      txt("titleA", "العنوان — الجزء الأول", "محاولة"),
      txt("titleAccent", "العنوان — كلمة مُلوّنة", "جادّة"),
      txt("titleB", "العنوان — الجزء الأخير", "لبناء شيءٍ مستدام في مكانٍ يفتقر إلى الاستقرار."),
      txt("chapter", "اسم الفصل", "الفصل الأوّل · المنشأ"),
      long("lead", "الجملة الافتتاحية الكبيرة", "وُلد Island Haven من إيمانٍ بأنّ الاستثمار الحقيقيّ هو في الإنسان قبل أيّ شيء آخر."),
      long("p1", "فقرة ١", "في غزّة، فقد كثيرون مساحاتهم الشخصيّة، وأدواتهم، وبيئة العمل التي اعتادوها — لكنّ الطاقة بقيت، والرغبة في البناء لم تنطفئ."),
      long("p2", "فقرة ٢", "جمعنا في غرفةٍ واحدةٍ ما تبقّى من إمكانات: مكاتب، إنترنت، كهرباء، وفوق ذلك كلّه — مجتمع. صار المكان مساحة نجاةٍ مهنيّةٍ لطلاب الجامعات، والخرّيجين الباحثين عن مسار، والمستقلّين الذين يحتاجون إلى بيئة عملٍ تليق بهم."),
      long("quote", "الاقتباس داخل البطاقة", "«Island Haven ليس مجرّد مساحةِ عمل. هو محاولة لإثبات أنّ المعرفة والخبرة والتعاون قادرةٌ على بناء مستقبل، حتى في أصعب الظروف.»"),
      img("image", "الصورة الجانبية", "/photos/IMG_8358.webp"),
      txt("creditEyebrow", "Eyebrow الاعتماد", "برنامج تنمويّ تابع لـ"),
      txt("creditTitle", "اسم المظلّة", "فريق «من الناس إلى الناس»"),
      long("creditBody", "نص المظلّة", "مبادرة تطوّعيّة تعمل من داخل غزّة وخارجها على إيصال الدعم المباشر إلى المشاريع المجتمعيّة الصغيرة. هي من احتضنت Island Haven وتُسهم في إبقاء أبوابه مفتوحة للجميع مجاناً."),
      url("creditLink1", "رابط الموقع التعريفي", "https://nastonas.org"),
      url("creditLink2", "رابط التبرّع", "https://nas2nas.org"),
      txt("stat1V", "إحصائية ١ — الرقم", "2024"),
      txt("stat1L", "إحصائية ١ — التسمية", "تأسّس"),
      txt("stat2V", "إحصائية ٢ — الرقم", "39"),
      txt("stat2L", "إحصائية ٢ — التسمية", "مقعد"),
      txt("stat3V", "إحصائية ٣ — الرقم", "100%"),
      txt("stat3L", "إحصائية ٣ — التسمية", "مجّانيّ"),
    ],
  },
  {
    key: "hours",
    label: "الموقع وقنوات التواصل",
    fields: [
      txt("label", "Eyebrow", "كل الأبواب مفتوحة"),
      txt("titleA", "العنوان — الجزء الأول", "تابعنا، سجّل،"),
      txt("titleB", "العنوان — الجزء الثاني", "أو"),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة", "زرنا."),
      long("sub", "النص الفرعي", "نحن متواجدون على كلّ المنصّات الرئيسيّة. اختر القناة التي تناسبك واختبر المساحة قبل أن تقرّر."),
      txt("locationEyebrow", "Eyebrow الموقع", "Where we are · أين نحن"),
      txt("locationTitle", "عنوان الموقع", "في قلب غزّة، على ضفّة المتوسّط."),
      long("locationBody", "نص الموقع", "المساحة في موقع آمن ومركزيّ نُرسله عبر الرسائل الخاصّة بعد تأكيد الانتساب. النقطة النابضة على الخريطة تدلّ على الحيّ تقريباً — لا الإحداثيّات الدقيقة."),
      txt("locationStatus", "حالة الزيارة", "مفتوح الآن للزوّار بموعد مسبق"),
      txt("locationCoords", "الإحداثيات", "٣١.٥٠° ش · ٣٤.٤٧° شرق"),
      txt("c1Ar", "قناة ١ — عربي", "Linktree الرسمي"),
      txt("c1En", "قناة ١ — إنجليزي", "All links"),
      long("c1Desc", "قناة ١ — الوصف", "كلّ روابطنا في مكان واحد، يشمل رابط الانتساب ومقعد الضيف."),
      url("c1Href", "قناة ١ — الرابط", "https://linktr.ee/ih_haven"),
      txt("c1Handle", "قناة ١ — العرض", "linktr.ee/ih_haven"),
      txt("c2Ar", "قناة ٢ — عربي", "نموذج التسجيل"),
      txt("c2En", "قناة ٢ — إنجليزي", "Apply"),
      long("c2Desc", "قناة ٢ — الوصف", "للانتساب إلى المجتمع — راجع معايير القبول قبل التقديم."),
      url("c2Href", "قناة ٢ — الرابط", "/apply"),
      txt("c2Handle", "قناة ٢ — العرض", "افتح النموذج"),
      txt("c3Ar", "قناة ٣ — عربي", "إنستغرام"),
      txt("c3En", "قناة ٣ — إنجليزي", "Instagram"),
      long("c3Desc", "قناة ٣ — الوصف", "آخر الأخبار، الورش، الفعاليّات، وصور من داخل المساحة."),
      url("c3Href", "قناة ٣ — الرابط", "https://www.instagram.com/ih_haven"),
      txt("c3Handle", "قناة ٣ — العرض", "@ih_haven"),
      txt("c4Ar", "قناة ٤ — عربي", "لينكدإن"),
      txt("c4En", "قناة ٤ — إنجليزي", "LinkedIn"),
      long("c4Desc", "قناة ٤ — الوصف", "الجانب المهنيّ من Island Haven — للشركات والشركاء والداعمين."),
      url("c4Href", "قناة ٤ — الرابط", "https://www.linkedin.com/company/ih-haven"),
      txt("c4Handle", "قناة ٤ — العرض", "Island Haven"),
      txt("c5Ar", "قناة ٥ — عربي", "فيسبوك"),
      txt("c5En", "قناة ٥ — إنجليزي", "Facebook"),
      long("c5Desc", "قناة ٥ — الوصف", "متابعة الأنشطة وقصص المنتسبين عبر صفحتنا الرسميّة."),
      url("c5Href", "قناة ٥ — الرابط", "https://www.facebook.com/islandhaven101"),
      txt("c5Handle", "قناة ٥ — العرض", "islandhaven101"),
      txt("c6Ar", "قناة ٦ — عربي", "زرنا في غزّة"),
      txt("c6En", "قناة ٦ — إنجليزي", "Visit"),
      long("c6Desc", "قناة ٦ — الوصف", "العنوان التفصيليّ يُرسَل عبر الرسائل الخاصّة لضمان السلامة."),
      url("c6Href", "قناة ٦ — الرابط", "https://www.instagram.com/ih_haven"),
      txt("c6Handle", "قناة ٦ — العرض", "راسلنا للعنوان"),
      long("bottomNote", "الملاحظة السفلية", "ضوابط استخدام المكان والتفاصيل الكاملة تُرسَل عند تأكيد الانتساب — راسلنا لأيّ سؤال."),
    ],
  },
  {
    key: "support",
    label: "ادعمنا (Support)",
    fields: [
      img("image", "صورة الخلفية", "/photos/IMG_8358.webp"),
      txt("eyebrow", "Eyebrow", "Stand with us · كن معنا"),
      txt("headlineA", "العنوان — الجزء الأول", "استمرار هذا المكان"),
      txt("headlineB", "العنوان — الجزء الثاني", "يعتمد على"),
      txt("headlineAccent", "العنوان — الكلمة المُلوّنة", "التكافل."),
      long("body", "النص الفرعي", "Island Haven ليس مشروعاً ربحيّاً. هو مجتمع يُبنى يوميّاً بأيدي داعميه ومنتسبيه — وكلّ مساهمة تُبقي الأبواب مفتوحة."),
      txt("donateEyebrow", "بطاقة التبرّع — Eyebrow", "Donate · تبرّع"),
      txt("donateSub", "بطاقة التبرّع — تحت Eyebrow", "عبر مبادرة من الناس إلى الناس"),
      txt("donateTitleA", "بطاقة التبرّع — العنوان (سطر ١)", "كلّ مساهمة تُبقي"),
      txt("donateTitleB", "بطاقة التبرّع — العنوان (سطر ٢)", "الأبواب مفتوحة."),
      long("donateBody", "بطاقة التبرّع — النص", "تكاليف تشغيل المساحة — من إنترنت وكهرباء وصيانة — يغطّيها داعمون مثلك. تبرّع مباشر وآمن، يصل ١٠٠٪ إلى التشغيل."),
      txt("donateCta", "بطاقة التبرّع — نص الزر", "تبرّع الآن"),
      url("donateHref", "بطاقة التبرّع — رابط", "https://nas2nas.org"),
      txt("donateNote", "بطاقة التبرّع — ملاحظة", "nas2nas.org"),
      txt("sec1Ar", "إجراء ١ — عربي", "انضمّ للمجتمع"),
      txt("sec1En", "إجراء ١ — إنجليزي", "Apply"),
      long("sec1Body", "إجراء ١ — النص", "إذا كنت في غزّة وتنطبق عليك المعايير، سجّل في نموذج الانتساب."),
      txt("sec1Cta", "إجراء ١ — نص الزر", "افتح النموذج"),
      url("sec1Href", "إجراء ١ — الرابط", "/apply"),
      txt("sec2Ar", "إجراء ٢ — عربي", "شارك القصّة"),
      txt("sec2En", "إجراء ٢ — إنجليزي", "Share"),
      long("sec2Body", "إجراء ٢ — النص", "تابعنا على وسائل التواصل، وأرسل صفحاتنا لكلّ من قد يهمّه الأمر."),
      txt("sec2Cta", "إجراء ٢ — نص الزر", "تابعنا"),
      url("sec2Href", "إجراء ٢ — الرابط", "https://www.instagram.com/ih_haven"),
    ],
  },
  {
    key: "footer",
    label: "تذييل الصفحة (Footer)",
    fields: [
      img("logo", "الشعار", "/logo.png"),
      txt("colophonEyebrow", "Eyebrow", "Colophon · شعار الكتاب"),
      txt("signOffA", "العنوان الكبير — الجزء الأول", "مساحة"),
      txt("signOffAccent", "العنوان الكبير — كلمة مُلوّنة", "تتّسع"),
      txt("signOffB", "العنوان الكبير — الجزء الأخير", "لأحلامك."),
      txt("estLabel", "ملاحظة التأسيس", "تأسّس ٢٠٢٤"),
      txt("placeLabel", "ملاحظة الموقع", "غزّة · فلسطين"),
      txt("brand", "اسم العلامة", "Island Haven"),
      long("aboutBody", "نص التعريف", "حاضنة أعمال في غزّة — نوفّر بيئة عمل للمستقلّين والخرّيجين وطلبة الجامعات، مع برامج تدريب وفرص تشبيك."),
      txt("indexLabel", "تسمية الفهرس", "فهرس"),
      txt("programmeLabel", "تسمية المظلّة", "رسالتنا"),
      txt("programmeTitle", "اسم المظلّة", "آيلاند هيفن"),
      long("programmeBody", "نص المظلّة", "حاضنة أعمال في غزّة تحتضن روّاد الأعمال والمستقلّين والخرّيجين، وتأخذهم من الفكرة إلى المنتج."),
      txt("bottomCopy", "حقوق النسخ", "© Island Haven · غزّة — فلسطين"),
      txt("bottomTag", "شعار سفلي", "بُني بحبّ ليتّسع لأحلامكم"),
    ],
  },
  {
    key: "header",
    label: "الهيدر (Header)",
    description: "شريط التنقّل العلوي — الشعار، روابط القائمة، زرّ الحجز، وزرّ الانتساب.",
    fields: [
      img("logo", "الشعار", "/logo.png"),
      txt("brand", "اسم العلامة (لاتيني)", "Island Haven"),
      txt("tagline", "تسمية تحت العلامة", "آيلاند هيفن · غزّة"),
      txt("nav1Label", "رابط ١ — التسمية", "الرئيسيّة"),
      txt("nav1En", "رابط ١ — إنجليزي", "Home"),
      txt("nav2Label", "رابط ٢ — التسمية", "منتسبو المساحة"),
      txt("nav2En", "رابط ٢ — إنجليزي", "Members"),
      txt("nav3Label", "رابط ٣ — التسمية", "البرنامج التّدريبيّ"),
      txt("nav3En", "رابط ٣ — إنجليزي", "Programs"),
      txt("nav4Label", "رابط ٤ — التسمية", "مُجتمعنا بالأرقام"),
      txt("nav4En", "رابط ٤ — إنجليزي", "Numbers"),
      txt("nav5Label", "رابط ٥ — التسمية", "فعاليّات آيلاند"),
      txt("nav5En", "رابط ٥ — إنجليزي", "Events"),
      txt("nav6Label", "رابط ٦ — التسمية", "معرض الصّور"),
      txt("nav6En", "رابط ٦ — إنجليزي", "Gallery"),
      txt("nav7Label", "رابط ٧ — التسمية", "من نحن"),
      txt("nav7En", "رابط ٧ — إنجليزي", "About"),
      txt("bookCtaLabel", "زرّ الحجز — التسمية", "احجز مقعد"),
      txt("ctaLabel", "زرّ الانتساب — التسمية", "انتسب الآن"),
      url("ctaHref", "زرّ الانتساب — الرابط", "/apply"),
      txt("menuLabel", "تسمية زرّ القائمة على الجوّال", "القائمة"),
    ],
  },
  {
    key: "gallery",
    label: "معرض الصور (Gallery)",
    description: "العنوان + ثماني عشرة صورة مع تعليق لكلٍّ منها.",
    fields: [
      txt("eyebrow", "Eyebrow", "Picture Essay · معرض الصور"),
      txt("titleA", "العنوان — الجزء الأول", "صورٌ من قلب"),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة", "المساحة."),
      long("sub", "النص الفرعي", "كلّ صورة هنا التُقطت داخل آيلاند هيفن — وجوه، تركيز، تفاصيل، وحياة يوميّة في مكان نُحبّه."),
      img("p01", "صورة ١", "/photos/IMG_8357.webp"),
      txt("c01", "تعليق ١", "صباحٌ في المساحة"),
      img("p02", "صورة ٢", "/photos/IMG_8300.webp"),
      txt("c02", "تعليق ٢", "الجدار الذي يحمل اسمنا"),
      img("p03", "صورة ٣", "/photos/IMG_8347.webp"),
      txt("c03", "تعليق ٣", "تركيزٌ عميق على التصميم"),
      img("p04", "صورة ٤", "/photos/IMG_8313.webp"),
      txt("c04", "تعليق ٤", "ركن العمل المشترك"),
      img("p05", "صورة ٥", "/photos/IMG_8352.webp"),
      txt("c05", "تعليق ٥", "ورشةٌ نتعلّم فيها معاً"),
      img("p06", "صورة ٦", "/photos/IMG_8344.webp"),
      txt("c06", "تعليق ٦", "زاوية هادئة للتفكير"),
      img("p07", "صورة ٧", "/photos/IMG_8358.webp"),
      txt("c07", "تعليق ٧", "تشبيكٌ بين الأرواح"),
      img("p08", "صورة ٨", "/photos/IMG_8346.webp"),
      txt("c08", "تعليق ٨", "جلسة عملٍ مفتوحة"),
      img("p09", "صورة ٩", "/photos/IMG_8341.webp"),
      txt("c09", "تعليق ٩", "حواراتٌ تُولد منها فرص"),
      img("p10", "صورة ١٠", "/photos/IMG_8345.webp"),
      txt("c10", "تعليق ١٠", "في انتظار البدء"),
      img("p11", "صورة ١١", "/photos/IMG_8349.webp"),
      txt("c11", "تعليق ١١", "أيدٍ تبني الغد"),
      img("p12", "صورة ١٢", "/photos/IMG_8353.webp"),
      txt("c12", "تعليق ١٢", "مساحةٌ تتّسع للتجربة"),
      img("p13", "صورة ١٣", "/photos/IMG_8356.webp"),
      txt("c13", "تعليق ١٣", "ضحكاتٌ بين الأقران"),
      img("p14", "صورة ١٤", "/photos/IMG_8303.webp"),
      txt("c14", "تعليق ١٤", "تفاصيل مكاننا"),
      img("p15", "صورة ١٥", "/photos/IMG_8304.webp"),
      txt("c15", "تعليق ١٥", "أمسيةٌ في الهيفن"),
      img("p16", "صورة ١٦", "/photos/IMG_8307.webp"),
      txt("c16", "تعليق ١٦", "حضورٌ مهنيّ"),
      img("p17", "صورة ١٧", "/photos/IMG_8308.webp"),
      txt("c17", "تعليق ١٧", "تركيزٌ جماعيّ"),
      img("p18", "صورة ١٨", "/photos/IMG_8314.webp"),
      txt("c18", "تعليق ١٨", "وجوهٌ نفخر بها"),
    ],
  },
  {
    key: "contact",
    label: "التواصل والروابط",
    fields: [
      url("instagram", "Instagram", "https://www.instagram.com/ih_haven"),
      url("linkedin", "LinkedIn", "https://www.linkedin.com/company/ih-haven"),
      url("facebook", "Facebook", "https://www.facebook.com/islandhaven101"),
      url("linktree", "Linktree", "https://linktr.ee/ih_haven"),
      url("nastonas", "موقع من الناس إلى الناس", "https://nastonas.org"),
      url("nas2nas", "رابط التبرّع", "https://nas2nas.org"),
      txt("email", "البريد الإلكتروني", "island-haven@nastonas.org"),
      txt("phone", "الهاتف", "+972 56-753-6815"),
      url("whatsapp", "واتساب", "https://wa.me/972567536815"),
    ],
  },
  {
    key: "newsSlider",
    label: "شريط الفعاليّات (Home)",
    description: "شريط فعاليّات آيلاند في الصفحة الرئيسيّة — العنوان، التسميات، والفراغ.",
    fields: [
      txt("eyebrow", "Eyebrow", "فعاليّات آيلاند · Events"),
      txt("title", "العنوان", "ما يحدث في المساحة هذا الأسبوع."),
      txt("ctaAll", "زرّ كلّ الفعاليّات", "كلّ الفعاليّات"),
      txt("ctaCard", "زرّ بطاقة الفعاليّة", "اقرأ المزيد"),
      txt("emptyText", "نص الفراغ", "لا توجد فعاليّات معلَنة بعد — تابعنا قريبًا."),
      txt("prevAria", "وصف زرّ السابق", "السّابق"),
      txt("nextAria", "وصف زرّ التالي", "التّالي"),
    ],
  },
  {
    key: "numbersBand",
    label: "شريط الأرقام (Home)",
    description: "شريط الأرقام الحقيقيّة في الرّئيسيّة — العنوان، التسميات، والزرّ.",
    fields: [
      txt("eyebrow", "Eyebrow", "الحاضنة بالأرقام"),
      txt("titleA", "العنوان — الجزء الأول", "ليست شعارات — "),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة", "أرقامٌ حقيقيّة."),
      txt("titleB", "العنوان — التتمّة (اختياريّ)", ""),
      long("sub", "النص الفرعي", "كلّ رقم هنا يأتي مباشرةً من قاعدة بياناتنا، ويتحدّث تلقائيًّا مع كلّ منتسبٍ جديد، كلّ عمل، وكلّ مقعد محجوز."),
      txt("ctaLabel", "زرّ عرض المزيد", "عرض المزيد"),
      txt("tile1Label", "بطاقة ١ — العربيّة", "منتسب"),
      txt("tile1En", "بطاقة ١ — الإنجليزيّة", "Members"),
      txt("tile2Label", "بطاقة ٢ — العربيّة", "عمل منشور"),
      txt("tile2En", "بطاقة ٢ — الإنجليزيّة", "Works"),
      txt("tile3Label", "بطاقة ٣ — العربيّة", "تسجيل في برامج"),
      txt("tile3En", "بطاقة ٣ — الإنجليزيّة", "Enrollments"),
      txt("tile4Label", "بطاقة ٤ — العربيّة", "مقعد استضفناه"),
      txt("tile4En", "بطاقة ٤ — الإنجليزيّة", "Seats hosted"),
    ],
  },
  {
    key: "venturesShowcase",
    label: "معرض المشاريع (Home)",
    description: "شريط المشاريع في الرئيسيّة — النصوص الثابتة فقط (المشاريع نفسها من قاعدة البيانات).",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "معرض المشاريع"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "The portfolio"),
      txt("titleLead", "العنوان — الجزء الأول (عربي)", "مشاريع وُلدت في "),
      txt("titleLeadEn", "العنوان — الجزء الأول (إنجليزي)", "Ventures built at "),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة (عربي)", "آيلاند."),
      txt("titleAccentEn", "العنوان — الكلمة المُلوّنة (إنجليزي)", "Island Haven."),
      long("sub", "النص الفرعي — عربي", "من فكرة على ورقة، إلى يوم عرضٍ أمام الدّاعمين، إلى منتجٍ يخدم النّاس — هذه المحفظة تنمو داخل مساحتنا في غزّة."),
      long("subEn", "النص الفرعي — إنجليزي", "From an idea on paper, to a Demo Day in front of our backers, to a product serving people — this portfolio is growing inside our space in Gaza."),
      txt("emptyKicker", "الفراغ — Eyebrow عربي", "الدفعة الأولى"),
      txt("emptyKickerEn", "الفراغ — Eyebrow إنجليزي", "Cohort 01"),
      txt("emptyTitle", "الفراغ — العنوان عربي", "أوّل دفعة تَبني الآن."),
      txt("emptyTitleEn", "الفراغ — العنوان إنجليزي", "The first cohort is building now."),
      long("emptyBody", "الفراغ — النص عربي", "هنا، قريبًا، تظهر أسماء المشاريع التي وُلدت في آيلاند — ومقعدك في الصفحة التالية."),
      long("emptyBodyEn", "الفراغ — النص إنجليزي", "This is where the names of ventures born at Island Haven will live — and your seat is on the next page."),
      txt("emptyCta", "الفراغ — زرّ عربي", "قدّم للدفعة الأولى"),
      txt("emptyCtaEn", "الفراغ — زرّ إنجليزي", "Apply to the first cohort"),
      txt("allCta", "زرّ كلّ المشاريع — عربي", "كلّ المشاريع"),
      txt("allCtaEn", "زرّ كلّ المشاريع — إنجليزي", "All ventures"),
    ],
  },
  {
    key: "successStories",
    label: "أصوات الأعضاء (Home)",
    description: "شريط قصص النجاح في الرئيسيّة — النصوص الثابتة فقط (الشهادات نفسها من قاعدة البيانات).",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "أصوات أعضائنا"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Voices of our members"),
      txt("title", "العنوان — الجزء الأول (عربي)", "أصواتٌ من "),
      txt("titleEn", "العنوان — الجزء الأول (إنجليزي)", "Voices from "),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة (عربي)", "الميدان."),
      txt("titleAccentEn", "العنوان — الكلمة المُلوّنة (إنجليزي)", "the ground."),
      txt("beliefLead", "القناعة — الجزء الأول (عربي)", "الموهبة لا تحدّها "),
      txt("beliefLeadEn", "القناعة — الجزء الأول (إنجليزي)", "Talent is not bound by "),
      txt("beliefAccent", "القناعة — الكلمة المُلوّنة (عربي)", "الجغرافيا"),
      txt("beliefAccentEn", "القناعة — الكلمة المُلوّنة (إنجليزي)", "geography"),
      txt("beliefTail", "القناعة — التتمّة (عربي)", "."),
      txt("beliefTailEn", "القناعة — التتمّة (إنجليزي)", "."),
      long("emptyBody", "الفراغ — النص عربي", "في غزّة كفاءاتٌ تستحقّ مقعدًا في الاقتصاد الرقميّ العالميّ — ومهمّتنا أن نوصلها إليه. أوّل من يقدّم اليوم، يكتب أوّل القصص."),
      long("emptyBodyEn", "الفراغ — النص إنجليزي", "Gaza holds talent that deserves a seat in the global digital economy — our mission is to get it there. Whoever applies today writes the first story."),
      txt("emptyAvatar", "الفراغ — حرف الأفاتار (عربي)", "آ"),
      txt("emptyAvatarEn", "الفراغ — حرف الأفاتار (إنجليزي)", "I"),
      txt("emptyAttribution", "الفراغ — سطر النسبة (عربي)", "فريق آيلاند هيفن — قناعتنا التأسيسيّة"),
      txt("emptyAttributionEn", "الفراغ — سطر النسبة (إنجليزي)", "The Island Haven team — our founding belief"),
      txt("emptyCta", "الفراغ — زرّ عربي", "اكتب أوّل قصّة"),
      txt("emptyCtaEn", "الفراغ — زرّ إنجليزي", "Write the first story"),
      txt("originalLabel", "شارة «الأصل عربي» — عربي", ""),
      txt("originalLabelEn", "شارة «الأصل عربي» — إنجليزي", "Original · Arabic"),
    ],
  },
  {
    key: "expertsBand",
    label: "الخبراء والمرشدون (Home)",
    description: "شريط الخبراء في الرئيسيّة — النصوص الثابتة فقط (بطاقات الخبراء والعدد من قاعدة البيانات).",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "الخبراء والمرشدون"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Experts & mentors"),
      txt("title", "العنوان — الجزء الأول (عربي)", "خبراءٌ يأخذون بيدك نحو "),
      txt("titleEn", "العنوان — الجزء الأول (إنجليزي)", "Experts who take your hand toward "),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة (عربي)", "الأثر."),
      txt("titleAccentEn", "العنوان — الكلمة المُلوّنة (إنجليزي)", "impact."),
      txt("titleEmpty", "الفراغ — العنوان — الجزء الأول (عربي)", "المرشدون يتجمّعون. "),
      txt("titleEmptyEn", "الفراغ — العنوان — الجزء الأول (إنجليزي)", "The mentors are gathering. "),
      txt("titleEmptyAccent", "الفراغ — العنوان — الكلمة المُلوّنة (عربي)", "كن منهم."),
      txt("titleEmptyAccentEn", "الفراغ — العنوان — الكلمة المُلوّنة (إنجليزي)", "Be one."),
      long("intro", "النص الفرعي — عربي", "احجز جلسة إرشاد فرديّة مَجّانًا، وحوّل فكرتك إلى مشروع قابل للنموّ."),
      long("introEn", "النص الفرعي — إنجليزي", "Book a free one-to-one session, and turn your idea into a venture that can scale."),
      long("introEmpty", "الفراغ — النص الفرعي — عربي", "مؤسّسون وبُناةٌ ومتخصّصون من حول العالم يجلسون مع جيلٍ غزّيّ شابّ، واحدًا لواحد. جلسة واحدة قد تفتح بابًا أغلقته الحرب."),
      long("introEmptyEn", "الفراغ — النص الفرعي — إنجليزي", "Founders, builders and specialists worldwide sit with a young Gazan generation, one to one. A single session can open a door the war had closed."),
      txt("availableSuffix", "لاحقة العدد المتاح — عربي", "متاحون للحجز الآن"),
      txt("availableSuffixEn", "لاحقة العدد المتاح — إنجليزي", "available to book now"),
      long("emptyBody", "الفراغ — نص البطاقة — عربي", "الروستر يتشكّل الآن. إن كنت مؤسّسًا أو متخصّصًا وتودّ أن تمنح ساعةً من وقتك، فكن أوّل المرشدين."),
      long("emptyBodyEn", "الفراغ — نص البطاقة — إنجليزي", "The roster is forming. If you're a founder or specialist willing to give an hour of your time, be one of the first mentors."),
      txt("emptyCta", "الفراغ — زرّ ١ عربي", "سجّل كمرشد"),
      txt("emptyCtaEn", "الفراغ — زرّ ١ إنجليزي", "Become a mentor"),
      txt("emptyCta2", "الفراغ — زرّ ٢ عربي", "كيف يعمل الإرشاد"),
      txt("emptyCta2En", "الفراغ — زرّ ٢ إنجليزي", "How mentorship works"),
      txt("bookLabel", "شارة «متاح» — عربي", "متاح للحجز"),
      txt("bookLabelEn", "شارة «متاح» — إنجليزي", "Available to book"),
      txt("busyLabel", "شارة «الانتظار» — عربي", "قائمة الانتظار"),
      txt("busyLabelEn", "شارة «الانتظار» — إنجليزي", "Waitlist"),
      txt("outroLine", "السطر الختامي — عربي", "كلّ الخبراء، في مكانٍ واحد."),
      txt("outroLineEn", "السطر الختامي — إنجليزي", "Every expert, in one place."),
      txt("allCta", "زرّ تصفّح الكلّ — عربي", "تصفّح كل الخبراء"),
      txt("allCtaEn", "زرّ تصفّح الكلّ — إنجليزي", "Browse all experts"),
    ],
  },
  {
    key: "featuredMembers",
    label: "مواهب المجتمع (Home)",
    description: "شريط المنتسبين في الرئيسيّة — النصوص الثابتة فقط (بطاقات المنتسبين من قاعدة البيانات).",
    fields: [
      txt("viewAll", "زرّ عرض الكلّ — عربي", "عرض الكلّ"),
      txt("viewAllEn", "زرّ عرض الكلّ — إنجليزي", "View all"),
      txt("eyebrow", "Eyebrow — عربي", "المجتمع"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Community"),
      txt("eyebrowAccent", "Eyebrow — الكلمة المُلوّنة (عربي)", "غزّة"),
      txt("eyebrowAccentEn", "Eyebrow — الكلمة المُلوّنة (إنجليزي)", "Gaza"),
      txt("title", "العنوان — الجزء الأول (عربي)", "مواهب "),
      txt("titleEn", "العنوان — الجزء الأول (إنجليزي)", "Talent that "),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة (عربي)", "تصنع الفارق"),
      txt("titleAccentEn", "العنوان — الكلمة المُلوّنة (إنجليزي)", "makes a difference"),
      txt("viewProfile", "زرّ عرض الملفّ — عربي", "عرض الملفّ"),
      txt("viewProfileEn", "زرّ عرض الملفّ — إنجليزي", "View profile"),
    ],
  },
  {
    key: "pageMembers",
    label: "صفحة المنتسبين",
    description: "ترويسة صفحة /members، حقل البحث، وفلاتر التصنيف.",
    fields: [
      txt("eyebrow", "Eyebrow", "من نحن"),
      txt("title", "العنوان", "منتسبو المساحة"),
      long("subtitle", "النص الفرعي", "مُجتمعٌ من المستقلّين، الخرّيجين، والطّلّاب يصنعون أعمالهم من قلب غزّة. تعرّف عليهم — واطّلع على أعمالهم."),
      txt("searchPlaceholder", "Placeholder البحث", "ابحث بالاسم، التّخصّص، أو المهارة…"),
      txt("filterAll", "فلتر — الكلّ", "الكلّ"),
      txt("filterFreelancer", "فلتر — مستقلّون", "مُستقلّون"),
      txt("filterGraduate", "فلتر — خرّيجون", "خرّيجون"),
      txt("filterStudent", "فلتر — طلّاب", "طلّاب"),
      txt("filterOther", "فلتر — أعضاء", "أعضاء"),
      txt("worksLabel", "تسمية «عمل»", "عمل"),
      txt("emptyTitle", "عنوان الفراغ", "لا توجد نتائج"),
      txt("emptyHint", "تلميح الفراغ", "جرّب فلترًا آخر أو كلمة بحث مختلفة."),
    ],
  },
  {
    key: "pageNumbers",
    label: "صفحة الأرقام",
    description: "ترويسة صفحة /numbers وعناوين المجموعات.",
    fields: [
      txt("eyebrow", "Eyebrow", "By the numbers"),
      txt("title", "العنوان", "مُجتمعنا بالأرقام"),
      long("subtitle", "النص الفرعي", "لا شيء هنا مكتوب يدويًّا. كلّ رقم يُحسب الآن من قاعدة بياناتنا — يتغيّر تلقائيًّا مع كلّ منتسب جديد، كلّ عمل، وكلّ مقعد محجوز."),
      txt("group1Title", "مجموعة ١ — العنوان", "المجتمع"),
      txt("group1En", "مجموعة ١ — Eyebrow", "Community"),
      txt("group2Title", "مجموعة ٢ — العنوان", "الإنتاج"),
      txt("group2En", "مجموعة ٢ — Eyebrow", "Output"),
      txt("group3Title", "مجموعة ٣ — العنوان", "الاستضافة"),
      txt("group3En", "مجموعة ٣ — Eyebrow", "Hospitality"),
      txt("tMembers", "بطاقة — إجمالي المنتسبين", "إجمالي المنتسبين"),
      txt("tFreelancers", "بطاقة — مستقلّون", "مُستقلّون"),
      txt("tGraduates", "بطاقة — خرّيجون", "خرّيجون"),
      txt("tStudents", "بطاقة — طلّاب", "طلّاب"),
      txt("tWorks", "بطاقة — أعمال منشورة", "عمل منشور في المعرض"),
      txt("tCourses", "بطاقة — برامج", "برنامج تدريبيّ"),
      txt("tEnrollments", "بطاقة — تسجيلات", "تسجيل في برامج"),
      txt("tBookings", "بطاقة — حجوزات", "حجز نشط"),
      txt("tSeats", "بطاقة — مقاعد", "مقعد استضفناه"),
      txt("tApplications", "بطاقة — طلبات", "طلب انتساب"),
      txt("tEvents", "بطاقة — منشورات وفعاليّات", "منشور · فعاليّة"),
    ],
  },
  {
    key: "pageGallery",
    label: "صفحة المعرض",
    description: "ترويسة صفحة /gallery ونصوص الفراغ.",
    fields: [
      txt("eyebrow", "Eyebrow", "Gallery"),
      txt("title", "العنوان", "معرض الصّور"),
      long("subtitle", "النص الفرعي", "مقتطفاتٌ من أعمال المنتسبين، ولحظاتٍ من حياة المساحة. اضغط أيّ صورة لعرضها بحجمها الكامل."),
      txt("emptyTitle", "عنوان الفراغ", "لا توجد صور بعد"),
      txt("emptyHint", "تلميح الفراغ", "ستظهر هنا تلقائيًّا مع كلّ عمل جديد."),
      txt("byAuthor", "تسمية «بقلم»", "بقلم"),
      txt("openWork", "زرّ افتح العمل", "افتح العمل"),
    ],
  },
  {
    key: "pageEvents",
    label: "صفحة الفعاليّات",
    description: "ترويسة صفحة /events وفلاتر النوع.",
    fields: [
      txt("eyebrow", "Eyebrow", "Events · ما يحدث"),
      txt("title", "العنوان", "فعاليّات آيلاند"),
      long("subtitle", "النص الفرعي", "جدولُ فعاليّاتنا، أخبارنا، ونصائحنا الأسبوعيّة — كلّ ما يحدث في المساحة في مكانٍ واحد."),
      txt("filterAll", "فلتر — الكلّ", "الكلّ"),
      txt("filterNews", "فلتر — أخبار", "أخبار"),
      txt("filterTip", "فلتر — نصائح", "نصائح"),
      txt("filterStory", "فلتر — قصص", "قصص"),
      txt("filterQuote", "فلتر — اقتباسات", "اقتباسات"),
      txt("emptyTitle", "عنوان الفراغ", "لا توجد فعاليّات بعد"),
      txt("emptyHint", "تلميح الفراغ", "ستظهر فعاليّاتنا القادمة هنا — تابعنا قريبًا."),
      txt("detailsLabel", "زرّ التفاصيل", "التفاصيل"),
    ],
  },
  {
    key: "pageMembership",
    label: "صفحة مجتمع المواهب",
    description: "ترويسة صفحة /membership، بطاقة الإحصاء، الفلاتر، والبحث.",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "مجتمع المواهب · TALENT"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Talent Community · مجتمع"),
      txt("title", "العنوان — عربي", "مواهب"),
      txt("titleEn", "العنوان — إنجليزي", "The talent"),
      txt("highlight", "الكلمة المُلوّنة — عربي", "غزّة"),
      txt("highlightEn", "الكلمة المُلوّنة — إنجليزي", "of Gaza"),
      long("subtitle", "النص الفرعي — عربي", "طلابٌ وخرّيجون ومستقلّون من آيلاند هيفن — مطوّرون، مصمّمون، ومحلّلو بيانات يبنون من قلب غزّة نحو العالم."),
      long("subtitleEn", "النص الفرعي — إنجليزي", "Students, graduates and freelancers of Island Haven — developers, designers and data analysts building from the heart of Gaza to the world."),
      txt("statLabel", "تسمية الإحصاء — عربي", "موهبة في المجتمع"),
      txt("statLabelEn", "تسمية الإحصاء — إنجليزي", "talents in the community"),
      txt("typeStudent", "تصنيف طالب — عربي", "طالب"),
      txt("typeStudentEn", "تصنيف طالب — إنجليزي", "Student"),
      txt("typeGraduate", "تصنيف خرّيج — عربي", "خريج"),
      txt("typeGraduateEn", "تصنيف خرّيج — إنجليزي", "Graduate"),
      txt("typeFreelancer", "تصنيف مستقلّ — عربي", "مستقلّ"),
      txt("typeFreelancerEn", "تصنيف مستقلّ — إنجليزي", "Freelancer"),
      txt("chipAll", "فلتر الكل — عربي", "الكل"),
      txt("chipAllEn", "فلتر الكل — إنجليزي", "All"),
      txt("chipStudent", "فلتر الطلاب — عربي", "الطلاب"),
      txt("chipStudentEn", "فلتر الطلاب — إنجليزي", "Students"),
      txt("chipGraduate", "فلتر الخرّيجين — عربي", "الخرّيجون"),
      txt("chipGraduateEn", "فلتر الخرّيجين — إنجليزي", "Graduates"),
      txt("chipFreelancer", "فلتر المستقلّين — عربي", "المستقلّون"),
      txt("chipFreelancerEn", "فلتر المستقلّين — إنجليزي", "Freelancers"),
      txt("searchPlaceholder", "Placeholder البحث — عربي", "ابحث…"),
      txt("searchPlaceholderEn", "Placeholder البحث — إنجليزي", "Search…"),
      txt("error", "رسالة الخطأ — عربي", "تعذّر تحميل المجتمع."),
      txt("errorEn", "رسالة الخطأ — إنجليزي", "Couldn't load the community."),
      txt("empty", "نص الفراغ — عربي", "لا نتائج مطابقة."),
      txt("emptyEn", "نص الفراغ — إنجليزي", "No matching talents."),
    ],
  },
  {
    key: "pageImpact",
    label: "صفحة الأثر",
    description: "ترويسة صفحة /impact، تسميات الإحصاءات، عنوان المهارات، وشريط التحقّق.",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "أثرنا · IMPACT"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Our Impact · أثرنا"),
      txt("title", "العنوان — عربي", "أثرٌ"),
      txt("titleEn", "العنوان — إنجليزي", "Impact you"),
      txt("highlight", "الكلمة المُلوّنة — عربي", "يُقاس"),
      txt("highlightEn", "الكلمة المُلوّنة — إنجليزي", "can measure"),
      long("subtitle", "النص الفرعي — عربي", "لا نقول «آلاف» بلا دليل. هذه أرقام مجتمعنا الحقيقيّة، من قاعدة بياناتنا مباشرةً — مواهب غزّة التي نأخذ بيدها نحو الاقتصاد الرقميّ."),
      long("subtitleEn", "النص الفرعي — إنجليزي", "We don't claim 'thousands' without proof. These are our community's real numbers, straight from our database — the Gaza talent we're guiding into the digital economy."),
      txt("stat1Label", "إحصاء ١ — عربي", "موهبة مُحتضَنة"),
      txt("stat1LabelEn", "إحصاء ١ — إنجليزي", "talents incubated"),
      txt("stat2Label", "إحصاء ٢ — عربي", "خرّيج جاهز للسوق"),
      txt("stat2LabelEn", "إحصاء ٢ — إنجليزي", "market-ready graduates"),
      txt("stat3Label", "إحصاء ٣ — عربي", "مستقلّ يعمل عالميًّا"),
      txt("stat3LabelEn", "إحصاء ٣ — إنجليزي", "freelancers working globally"),
      txt("stat4Label", "إحصاء ٤ — عربي", "من النساء"),
      txt("stat4LabelEn", "إحصاء ٤ — إنجليزي", "are women"),
      txt("skillsTitle", "عنوان المهارات — عربي", "أبرز المهارات"),
      txt("skillsTitleEn", "عنوان المهارات — إنجليزي", "Top skills"),
      long("verifyNote", "ملاحظة التحقّق — عربي", "أرقامنا العلنيّة موقّعة تشفيريًّا — تحقّق منها بنفسك."),
      long("verifyNoteEn", "ملاحظة التحقّق — إنجليزي", "Our public numbers are cryptographically signed — verify them yourself."),
      txt("verifyCta", "زرّ التحقّق — عربي", "تحقّق"),
      txt("verifyCtaEn", "زرّ التحقّق — إنجليزي", "Verify"),
      txt("meetCta", "زرّ قابِل المواهب — عربي", "قابِل المواهب"),
      txt("meetCtaEn", "زرّ قابِل المواهب — إنجليزي", "Meet the talent"),
    ],
  },
  {
    key: "pageHackathon",
    label: "صفحة الهاكاثون",
    description: "ترويسة صفحة /hackathon، المراحل الأربع، ملاحظة الدورة القادمة، والأزرار.",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "هاكاثون · HACKATHON"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Hackathon · هاكاثون"),
      txt("title", "العنوان — عربي", "تُبنى الأفكار"),
      txt("titleEn", "العنوان — إنجليزي", "Ideas built"),
      txt("highlight", "الكلمة المُلوّنة — عربي", "في أيّام"),
      txt("highlightEn", "الكلمة المُلوّنة — إنجليزي", "in days"),
      long("subtitle", "النص الفرعي — عربي", "هاكاثون آيلاند هيفن: تحدٍّ واقعيّ، فرقٌ من مواهب غزّة، إرشادٌ مباشر، ثمّ يوم عرضٍ أمام شبكة الدّاعمين. من الفكرة إلى الأثر في أيّام معدودة."),
      long("subtitleEn", "النص الفرعي — إنجليزي", "The Island Haven hackathon: a real-world challenge, teams of Gaza talent, hands-on mentorship, then a demo day before our network of backers. From idea to impact in a handful of days."),
      txt("step1Title", "مرحلة ١ — العنوان عربي", "الفكرة"),
      txt("step1TitleEn", "مرحلة ١ — العنوان إنجليزي", "Ideate"),
      long("step1Body", "مرحلة ١ — النص عربي", "تحدٍّ واقعيّ من شركائنا — تبدأ من مشكلة حقيقيّة، لا من ورقة بيضاء."),
      long("step1BodyEn", "مرحلة ١ — النص إنجليزي", "A real challenge from our partners — you start from a genuine problem, not a blank page."),
      txt("step2Title", "مرحلة ٢ — العنوان عربي", "الفريق"),
      txt("step2TitleEn", "مرحلة ٢ — العنوان إنجليزي", "Team up"),
      long("step2Body", "مرحلة ٢ — النص عربي", "فرقٌ من مواهب آيلاند هيفن: مطوّرون، مصمّمون، ومحلّلو بيانات جنبًا إلى جنب."),
      long("step2BodyEn", "مرحلة ٢ — النص إنجليزي", "Teams from Island Haven's talent: developers, designers and data analysts side by side."),
      txt("step3Title", "مرحلة ٣ — العنوان عربي", "البناء"),
      txt("step3TitleEn", "مرحلة ٣ — العنوان إنجليزي", "Build"),
      long("step3Body", "مرحلة ٣ — النص عربي", "أيّامٌ مكثّفة مع إرشاد مباشر من خبرائنا — من الفكرة إلى نموذج يعمل."),
      long("step3BodyEn", "مرحلة ٣ — النص إنجليزي", "Intense days with hands-on mentorship from our experts — from idea to a working prototype."),
      txt("step4Title", "مرحلة ٤ — العنوان عربي", "العرض"),
      txt("step4TitleEn", "مرحلة ٤ — العنوان إنجليزي", "Pitch"),
      long("step4Body", "مرحلة ٤ — النص عربي", "يوم عرضٍ أمام شبكة الدّاعمين والمستثمرين — أفضل الفرق تُفتح لها أبواب."),
      long("step4BodyEn", "مرحلة ٤ — النص إنجليزي", "A demo day before our network of backers and investors — doors open for the best teams."),
      txt("noteTitle", "ملاحظة الدورة — العنوان عربي", "الدورة القادمة قيد الإعداد"),
      txt("noteTitleEn", "ملاحظة الدورة — العنوان إنجليزي", "The next edition is in the works"),
      long("noteBody", "ملاحظة الدورة — النص عربي", "نُعلن مواعيد الهاكاثون القادم وتحدّياته عبر قنواتنا. سجّل اهتمامك الآن لتكون أوّل من يعرف — وانضمّ إلى مجتمع المواهب استعدادًا."),
      long("noteBodyEn", "ملاحظة الدورة — النص إنجليزي", "We announce the next hackathon's dates and challenges through our channels. Register your interest now to be the first to know — and join the talent community to get ready."),
      txt("applyCta", "زرّ التقديم — عربي", "قدّم على الحاضنة"),
      txt("applyCtaEn", "زرّ التقديم — إنجليزي", "Apply to the incubator"),
      txt("meetCta", "زرّ قابِل المواهب — عربي", "قابِل المواهب"),
      txt("meetCtaEn", "زرّ قابِل المواهب — إنجليزي", "Meet the talent"),
    ],
  },
  {
    key: "pageStories",
    label: "صفحة قصص النجاح",
    description: "ترويسة صفحة /stories، التسميات، نص الفراغ، وزرّ الدعوة.",
    fields: [
      txt("eyebrow", "Eyebrow — عربي", "إلهام حقيقيّ · إثبات لا يُجادَل · تأثير يتجاوز الحدود"),
      txt("eyebrowEn", "Eyebrow — إنجليزي", "Real Inspiration · Undeniable Proof · Impact Beyond Borders"),
      txt("title", "العنوان — عربي", "قصص"),
      txt("titleEn", "العنوان — إنجليزي", "Success"),
      txt("highlight", "الكلمة المُلوّنة — عربي", "النجاح"),
      txt("highlightEn", "الكلمة المُلوّنة — إنجليزي", "Stories"),
      long("subtitle", "النص الفرعي — عربي", "قصص حقيقيّة من داخل آيلاند — مشاريع بدأت بفكرة جريئة، ومواهب أبت أن تستسلم للظروف، وإرادات أثبتت أنّ الموهبة الغزيّة لا سقف لها."),
      long("subtitleEn", "النص الفرعي — إنجليزي", "Real stories from inside Island Haven — projects that started with a bold idea, talents that refused to yield to circumstances, and wills that proved Gazan talent has no ceiling."),
      txt("empty", "نص الفراغ — عربي", "لا قصص منشورة بعد."),
      txt("emptyEn", "نص الفراغ — إنجليزي", "No stories published yet."),
      txt("featuredBadge", "شارة مميّز — عربي", "مميّز"),
      txt("featuredBadgeEn", "شارة مميّز — إنجليزي", "Featured"),
      txt("readMore", "زرّ اقرأ القصة — عربي", "اقرأ القصة كاملة"),
      txt("readMoreEn", "زرّ اقرأ القصة — إنجليزي", "Read the full story"),
      txt("featuredStories", "عنوان القصص المميّزة — عربي", "قصص مميّزة"),
      txt("featuredStoriesEn", "عنوان القصص المميّزة — إنجليزي", "Featured Stories"),
      txt("allStories", "عنوان كل القصص — عربي", "كل القصص"),
      txt("allStoriesEn", "عنوان كل القصص — إنجليزي", "All Stories"),
      txt("ctaQuestion", "سؤال الدعوة — عربي", "هل تريد أن تكون القصّة التالية؟"),
      txt("ctaQuestionEn", "سؤال الدعوة — إنجليزي", "Want to be the next story?"),
      txt("ctaButton", "زرّ الدعوة — عربي", "قدّم على الحاضنة ←"),
      txt("ctaButtonEn", "زرّ الدعوة — إنجليزي", "Apply to the incubator →"),
    ],
  },
  {
    key: "applyForm",
    label: "صفحة الانتساب (Apply)",
    description: "كلّ نصوص فورم الانتساب — الترويسة، التسميات، التصنيفات، أزرار الإرسال، وشاشة النّجاح.",
    fields: [
      // Header chrome
      txt("backLabel", "زرّ العودة", "العودة"),
      txt("brandLatin", "اسم العلامة (لاتيني)", "Island Haven"),
      txt("brandArabic", "اسم العلامة (عربي)", "آيلاند هيفن"),
      // Hero block
      txt("eyebrow", "Eyebrow علوي", "طلب انتساب"),
      txt("titleLead", "العنوان — مقدّمة", "انضمّ إلى"),
      txt("titleAccent", "العنوان — الكلمة المُلوّنة", "آيلاند هيفن"),
      long("subtitle", "النص الفرعي", "حاضنة أعمال تتّسع لأحلامك في غزّة. املأ الطلب وسنتواصل معك على واتساب خلال أيّام."),
      // Section 01 — identity
      txt("sec1Title", "عنوان قسم ١", "مَن أنت"),
      txt("sec1Sub", "Eyebrow قسم ١", "Identity"),
      txt("fullNameLabel", "تسمية الاسم", "الاسم الكامل"),
      txt("fullNameHint", "تلميح الاسم", "Full name"),
      txt("fullNamePlaceholder", "Placeholder الاسم", "مثال: ياسمين الغزّاوي"),
      txt("emailLabel", "تسمية البريد", "البريد الإلكتروني"),
      txt("emailHint", "تلميح البريد", "Email"),
      txt("emailPlaceholder", "Placeholder البريد", "name@example.com"),
      txt("phoneLabel", "تسمية الهاتف", "رقم الواتساب"),
      txt("phoneHint", "تلميح الهاتف", "WhatsApp"),
      txt("phonePlaceholder", "Placeholder الهاتف", "+970 …"),
      // Section 02 — category
      txt("sec2Title", "عنوان قسم ٢", "ما تصنيفك"),
      txt("sec2Sub", "Eyebrow قسم ٢", "Category"),
      txt("cat1Label", "تصنيف ١ — العربي", "مستقلّ"),
      txt("cat1Sub", "تصنيف ١ — الإنجليزي", "Freelancer"),
      txt("cat2Label", "تصنيف ٢ — العربي", "خرّيج جامعي"),
      txt("cat2Sub", "تصنيف ٢ — الإنجليزي", "Graduate"),
      txt("cat3Label", "تصنيف ٣ — العربي", "طالب جامعي"),
      txt("cat3Sub", "تصنيف ٣ — الإنجليزي", "Student"),
      txt("cat4Label", "تصنيف ٤ — العربي", "غير ذلك"),
      txt("cat4Sub", "تصنيف ٤ — الإنجليزي", "Other"),
      // Section 03 — bio
      txt("sec3Title", "عنوان قسم ٣", "حدّثنا عنك"),
      txt("sec3Sub", "Eyebrow قسم ٣", "About you"),
      txt("bioLabel", "تسمية النبذة", "نبذة ومجال عملك"),
      txt("bioHint", "تلميح النبذة", "Bio"),
      long("bioPlaceholder", "Placeholder النبذة", "ماذا تعمل أو تدرس؟ ما الذي تنوي تحقيقه في آيلاند هيفن؟"),
      // Submit + footer trust
      txt("submitLabel", "زرّ الإرسال", "أرسل طلب الانتساب"),
      txt("submitLoading", "نص أثناء الإرسال", "جارٍ الإرسال…"),
      long("consentLine", "سطر الموافقة", "بإرسالك الطلب، توافق على أن نتواصل معك بشأنه فقط."),
      txt("trustLabel", "تسمية «بُني في»", "بُني في غزّة"),
      txt("trustBrand", "الشعار الإنجليزي", "Made in Gaza"),
      // Errors
      txt("errFallback", "خطأ — رسالة افتراضيّة", "تعذّر إرسال الطلب"),
      txt("errNetwork", "خطأ — الشبكة", "تعذّر الاتّصال بالخادم. حاول مجدّدًا بعد قليل."),
      // Success screen
      txt("successEyebrow", "نجاح — Eyebrow", "وصل طلبك"),
      txt("successThanksLead", "نجاح — مقدّمة الشكر", "شكرًا لك يا"),
      txt("successFallbackName", "نجاح — اسم افتراضي", "صديقنا"),
      long("successBody", "نجاح — النص", "استلمنا طلبك بأمان. سنراجعه ونتواصل معك على واتساب خلال أيّام.\nمرحبًا بك في عائلة آيلاند هيفن."),
      txt("successRefLabel", "نجاح — تسمية رقم الطلب", "رقم الطلب"),
      txt("successCta", "نجاح — زرّ العودة", "العودة للرئيسيّة"),
      // Document title
      txt("docTitle", "عنوان التبويب (Tab)", "انضمّ إلى آيلاند هيفن"),
    ],
  },
  {
    key: "gazaToGlobal",
    label: "من غزّة إلى العالم (Gaza → Global)",
    description: "قسم الوصول العالميّ — العنوان والأرقام الأربعة وخريطة الوصول.",
    fields: [
      txt("eyebrow", "eyebrow", "وصولٌ بلا حدود"),
      txt("eyebrowEn", "English", "Reach without borders"),
      txt("headlineLead", "headlineLead", "من غزّة "),
      txt("headlineLeadEn", "English", "From Gaza "),
      txt("headlineAccent", "headlineAccent", "إلى العالم."),
      txt("headlineAccentEn", "English", "to the world."),
      long("description", "description", "الموهبة لا تحدّها الجغرافيا. نفتح الباب من قلب غزّة إلى سوقٍ عالميّ، بمدفوعاتٍ تَعبر الحدود وشبكةٍ تمتدّ عبر القارّات."),
      long("descriptionEn", "English", "Talent isn't bounded by geography. From the heart of Gaza we open the door to a global market — with payments that cross borders and a network that spans continents."),
      txt("statsLabel", "statsLabel", "الوصول بالأرقام"),
      txt("statsLabelEn", "English", "Reach in numbers"),
      txt("stat0Value", "stat0Value", "190+"),
      txt("stat0Label", "stat0Label", "دولة حول العالم"),
      txt("stat0LabelEn", "English", "countries reached"),
      txt("stat0Sub", "stat0Sub", "سوق عمل عالميّ عبر الحدود"),
      txt("stat0SubEn", "English", "Global work marketplace"),
      txt("stat1Value", "stat1Value", "100%"),
      txt("stat1Label", "stat1Label", "مدفوعات Payoneer إلى غزّة"),
      txt("stat1LabelEn", "English", "Payoneer payouts to Gaza"),
      txt("stat1Sub", "stat1Sub", "تحويلات دوليّة تصل غزّة"),
      txt("stat1SubEn", "English", "International payments in"),
      txt("stat2Value", "stat2Value", "$25K"),
      txt("stat2Label", "stat2Label", "رصيد خدمات سحابيّة"),
      txt("stat2LabelEn", "English", "cloud credits"),
      txt("stat2Sub", "stat2Sub", "أدوات وبنية جاهزة"),
      txt("stat2SubEn", "English", "Tooling & infrastructure"),
      txt("stat3Value", "stat3Value", "40+"),
      txt("stat3Label", "stat3Label", "مُرشدون وشركاء"),
      txt("stat3LabelEn", "English", "mentors & partners"),
      txt("stat3Sub", "stat3Sub", "شبكة عالميّة"),
      txt("stat3SubEn", "English", "Global network"),
      txt("closingLead", "closingLead", "موهبتك من غزّة — "),
      txt("closingLeadEn", "English", "Your talent is from Gaza — "),
      txt("closingAccent", "closingAccent", "وأثرها للعالم كلّه."),
      txt("closingAccentEn", "English", "its impact is for the whole world."),
      txt("originLabel", "originLabel", "غزّة"),
      txt("originLabelEn", "English", "Gaza"),
      txt("legendOrigin", "legendOrigin", "نقطة الانطلاق: غزّة"),
      txt("legendOriginEn", "English", "Origin: Gaza"),
      txt("legendHint", "legendHint", "مرّر أو انتقل بين الوجهات"),
      txt("legendHintEn", "English", "Hover or tab through the destinations"),
      txt("region0", "region0", "أوروبا"),
      txt("region0En", "English", "Europe"),
      txt("reach0", "reach0", "أعضاؤنا يعملون مع عملاء وشركاء هنا."),
      txt("reach0En", "English", "Our members work with clients & partners here."),
      txt("region1", "region1", "أمريكا الشماليّة"),
      txt("region1En", "English", "North America"),
      txt("reach1", "reach1", "مشاريع تُسلَّم عبر الأطلسي من قلب غزّة."),
      txt("reach1En", "English", "Projects delivered across the Atlantic from Gaza."),
      txt("region2", "region2", "الخليج"),
      txt("region2En", "English", "The Gulf"),
      txt("reach2", "reach2", "شراكات ومهمّات مع فرقٍ في المنطقة."),
      txt("reach2En", "English", "Partnerships & engagements with teams in the region."),
      txt("region3", "region3", "آسيا"),
      txt("region3En", "English", "Asia"),
      txt("reach3", "reach3", "عملٌ عن بُعد يصل أسواقًا في القارّة."),
      txt("reach3En", "English", "Remote work reaching markets across the continent."),
      txt("region4", "region4", "إفريقيا"),
      txt("region4En", "English", "Africa"),
      txt("reach4", "reach4", "تعاونٌ يمتدّ جنوبًا عبر الحدود."),
      txt("reach4En", "English", "Collaboration reaching south, across borders."),
    ],
  },
  {
    key: "whatYouGet",
    label: "ما تحصل عليه (What you get)",
    description: "قيم العضويّة الأربع + الترويسة.",
    fields: [
      txt("eyebrow", "eyebrow", "ما تحصل عليه · غزّة"),
      txt("eyebrowEn", "English", "What you get · Gaza"),
      txt("headlineA", "headlineA", "حاضنة كاملة. "),
      txt("headlineAEn", "English", "A full incubator. "),
      txt("headlineAccent", "headlineAccent", "مجّانًا."),
      txt("headlineAccentEn", "English", "Free."),
      long("sub", "sub", "مساحة، إرشاد، برامج، وشبكة — كلّ ما يحتاجه صانعٌ ليبدأ ويَنمو، من قلب غزّة."),
      long("subEn", "English", "Space, mentorship, programs and a network — everything a maker needs to start and grow, from the heart of Gaza."),
      txt("learnMore", "learnMore", "اعرف أكثر"),
      txt("learnMoreEn", "English", "Learn more"),
      txt("seatsLabel", "seatsLabel", "مقعدًا في المساحة"),
      txt("seatsLabelEn", "English", "seats in the space"),
      txt("item0Title", "item0Title", "مساحة عمل مجّانيّة"),
      txt("item0TitleEn", "English", "A free workspace"),
      long("item0Body", "item0Body", "مقعد ثابت في مساحة هادئة، بإنترنت موثوق وكهرباء — احجزه متى احتجت."),
      long("item0BodyEn", "English", "A reliable seat in a calm space with stable internet and power — book it whenever you need."),
      txt("item1Title", "item1Title", "إرشاد من خبراء"),
      txt("item1TitleEn", "English", "Expert mentorship"),
      long("item1Body", "item1Body", "جلسات فرديّة مع مرشدين وروّاد أعمال ومتخصّصين — هندسةً وتصميمًا وأعمالًا."),
      long("item1BodyEn", "English", "1:1 sessions with mentors, founders and specialists — engineering, design and business."),
      txt("item2Title", "item2Title", "برامج ودفعات + Demo Day"),
      txt("item2TitleEn", "English", "Programs, cohorts & Demo Day"),
      long("item2Body", "item2Body", "مسارات احتضان وتسريع منظّمة، تُختم بيوم عرضٍ أمام شبكة من الدّاعمين."),
      long("item2BodyEn", "English", "Structured incubation & acceleration tracks that culminate in a Demo Day to our network."),
      txt("item3Title", "item3Title", "شبكة ومجتمع"),
      txt("item3TitleEn", "English", "A network & community"),
      long("item3Body", "item3Body", "مجتمع من المستقلّين والخرّيجين والمؤسّسين — تعاون، أعمال، وفرص."),
      long("item3BodyEn", "English", "A community of freelancers, graduates and founders — collaboration, work and opportunity."),
    ],
  },
  {
    key: "credibilityBar",
    label: "شريط المصداقيّة (Credibility bar)",
    description: "سطر الدّاعمين والأدوات التي نفتحها.",
    fields: [
      txt("founded", "founded", "تأسّست ٢٠٢٤"),
      txt("foundedEn", "English", "Founded 2024"),
      txt("free100", "free100", "١٠٠٪ مجّانًا"),
      txt("free100En", "English", "100% free"),
      txt("backedBy", "backedBy", "بدعم من"),
      txt("backedByEn", "English", "Backed by"),
      txt("backer1", "backer1", "NasToNas"),
      txt("and", "and", " و "),
      txt("andEn", "English", " & "),
      txt("backer2", "backer2", "Gaza Sky Geeks"),
      txt("toolsLabel", "toolsLabel", "أدوات نفتحها لك"),
      txt("toolsLabelEn", "English", "Tools we unlock"),
      txt("tool0", "tool0", "Replit"),
      txt("tool1", "tool1", "AWS Activate"),
      txt("tool2", "tool2", "Google for Startups"),
      txt("tool3", "tool3", "Payoneer"),
      txt("tool4", "tool4", "Freelancer"),
    ],
  },
  {
    key: "finalCta",
    label: "الدعوة الختاميّة (Final CTA)",
    description: "القسم الأخير — العنوان والأزرار ورابط واتساب.",
    fields: [
      txt("eyebrow", "eyebrow", "خطوتك الأخيرة"),
      txt("eyebrowEn", "English", "Your last step"),
      txt("headlineA", "headlineA", "طريقك للعالم يبدأ "),
      txt("headlineAEn", "English", "Your path to the world starts "),
      txt("headlineAccent", "headlineAccent", "بمقعد في غزّة."),
      txt("headlineAccentEn", "English", "with a seat in Gaza."),
      long("sub", "sub", "حاضنة كاملة — مجّانًا. قدّم اليوم، أو احجز مقعدك في المساحة وتعرّف علينا عن قرب."),
      long("subEn", "English", "A full incubator — free. Apply today, or book a seat in the space and get to know us up close."),
      txt("applyCta", "applyCta", "قدّم على الحاضنة"),
      txt("applyCtaEn", "English", "Apply to the incubator"),
      txt("bookCta", "bookCta", "احجز مقعدك"),
      txt("bookCtaEn", "English", "Book a seat"),
      txt("whatsappLabel", "whatsappLabel", "تحدّث معنا واتساب"),
      txt("whatsappLabelEn", "English", "Chat on WhatsApp"),
    ],
  },
  {
    key: "trustStrip",
    label: "شريط الثقة (Trust strip)",
    description: "مؤشّرات المصداقيّة المدمجة.",
    fields: [
      txt("item0Value", "item0Value", "تأسّست ٢٠٢٤"),
      long("item0ValueEn", "English", "Est. 2024"),
      txt("item0Label", "item0Label", "نعمل من قلب غزّة"),
      txt("item0LabelEn", "English", "Operating from Gaza"),
      txt("item1Value", "item1Value", "١٠٠٪"),
      txt("item1ValueEn", "English", "100%"),
      txt("item1Label", "item1Label", "مجّانًا للأعضاء"),
      txt("item1LabelEn", "English", "Free for members"),
      txt("item2Label", "item2Label", "عضو في المجتمع"),
      txt("item2LabelEn", "English", "Community members"),
      txt("item3Value", "item3Value", "عالميّة"),
      txt("item3ValueEn", "English", "Global"),
      txt("item3Label", "item3Label", "شبكة شركاء وفرص"),
      txt("item3LabelEn", "English", "Partners & opportunities"),
    ],
  },
  {
    key: "applyProcess",
    label: "خطوات التقديم (Apply process)",
    description: "من التقديم إلى Demo Day — الخطوات الأربع.",
    fields: [
      txt("eyebrow", "eyebrow", "كيف تنضمّ"),
      txt("eyebrowEn", "English", "How to join"),
      txt("titleA", "titleA", "من طلبٍ واحد،"),
      txt("titleAEn", "English", "From one application,"),
      txt("titleB", "titleB", "إلى يوم العرض."),
      txt("titleBEn", "English", "to Demo Day."),
      long("sub", "sub", "أربع خطوات واضحة، بلا رسوم وبلا غموض — هكذا تنتقل من فكرة إلى دفعة تُطلِق مشروعك."),
      long("subEn", "English", "Four clear steps — no fees, no fog. This is how you go from an idea to a cohort that launches your project."),
      txt("step0Title", "step0Title", "تقدّم بطلبك"),
      txt("step0TitleEn", "English", "Apply"),
      long("step0Body", "step0Body", "نموذج واحد، ١٥–٣٠ دقيقة. أخبرنا مَن أنت وماذا تبني — والصراحة تُقوّي طلبك."),
      long("step0BodyEn", "English", "One form, 15–30 minutes. Tell us who you are and what you're building — candor strengthens your case."),
      txt("step1Title", "step1Title", "المراجعة والمقابلة"),
      txt("step1TitleEn", "English", "Review & interview"),
      long("step1Body", "step1Body", "يقرأ الفريق كلّ طلب، ثمّ مقابلة قصيرة. نردّ خلال أيّام — قُبِلت أو لم تُقبَل، بتغذية راجعة واضحة."),
      long("step1BodyEn", "English", "The team reads every application, then a short interview. We respond within days — accepted or not, with clear feedback."),
      txt("step2Title", "step2Title", "الانضمام إلى دفعة"),
      txt("step2TitleEn", "English", "Onboard into a cohort"),
      long("step2Body", "step2Body", "تنضمّ إلى دفعة من المؤسّسين والمستقلّين — مساحة، إرشاد، ورشات، وخارطة طريق واضحة لمشروعك."),
      long("step2BodyEn", "English", "You join a cohort of founders and freelancers — space, mentorship, workshops and a clear roadmap for your project."),
      txt("step3Title", "step3Title", "يوم العرض"),
      txt("step3TitleEn", "English", "Demo Day"),
      long("step3Body", "step3Body", "تختم الرحلة بعرض مشروعك أمام شبكتنا من الداعمين والمرشدين والفرص — هنا يبدأ ما بعد آيلاند."),
      long("step3BodyEn", "English", "Close the journey by presenting to our network of supporters, mentors and opportunities — where life after Island Haven begins."),
      txt("cohortOpen", "cohortOpen", "التقديم مفتوح الآن"),
      txt("cohortOpenEn", "English", "Applications open now"),
      txt("cohortNext", "cohortNext", "الدفعة القادمة"),
      txt("cohortNextEn", "English", "Next cohort"),
      txt("cohortStarts", "cohortStarts", "تبدأ"),
      txt("cohortStartsEn", "English", "starts"),
      txt("cohortRolling", "cohortRolling", "التقديم مفتوح على مدار العام — والدفعة القادمة قريبًا."),
      long("cohortRollingEn", "English", "Rolling admissions, all year round — the next cohort is coming soon."),
      txt("ctaProcess", "ctaProcess", "تفاصيل عمليّة القبول"),
      txt("ctaProcessEn", "English", "See the full process"),
      txt("ctaCohorts", "ctaCohorts", "استعرض الدفعات"),
      txt("ctaCohortsEn", "English", "Browse cohorts"),
    ],
  },
  {
    key: "seatsBoard",
    label: "لوحة المقاعد (Seats board)",
    description: "قسم توفّر المقاعد على الرئيسيّة.",
    fields: [
      txt("eyebrow", "eyebrow", "توفّر المقاعد"),
      txt("eyebrowEn", "English", "Seat availability"),
      txt("place", "place", "غزّة"),
      txt("placeEn", "English", "Gaza"),
      txt("headlineSeats", "headlineSeats", "مقعد — "),
      txt("headlineSeatsEn", "English", "seats — "),
      txt("headlineAccent", "headlineAccent", "مكانك محفوظ."),
      txt("headlineAccentEn", "English", "your place is waiting."),
      long("descLive", "descLive", "قاعة كاملة، ثمانيةٌ وثلاثون مقعدًا حقيقيًّا في قلب غزّة. هذا ما هو متاح الآن — من قاعدة بياناتنا مباشرةً، لا رقم مُختلَق."),
      long("descLiveEn", "English", "A full hall — thirty-eight real seats in the heart of Gaza. This is what's open right now, straight from our database. No invented numbers."),
      long("descFallback", "descFallback", "قاعة كاملة، ثمانيةٌ وثلاثون مقعدًا حقيقيًّا في قلب غزّة. احجز مكانك وابدأ رحلتك معنا."),
      long("descFallbackEn", "English", "A full hall — thirty-eight real seats in the heart of Gaza. Reserve your place and start your journey with us."),
      txt("legendTaken", "legendTaken", "مشغول"),
      txt("legendTakenEn", "English", "taken"),
      txt("legendPresent", "legendPresent", "حاضر الآن"),
      txt("legendPresentEn", "English", "present now"),
      txt("legendFree", "legendFree", "متاح الآن"),
      txt("legendFreeEn", "English", "free now"),
      txt("captionSeats", "captionSeats", "مقعد"),
      txt("captionSeatsEn", "English", "seats"),
      txt("captionFree", "captionFree", "متاح"),
      txt("captionFreeEn", "English", "free"),
      txt("noFake", "noFake", "لا رقم مُختلَق"),
      txt("noFakeEn", "English", "no fake number"),
      txt("keyAvailable", "keyAvailable", "متاح"),
      txt("keyAvailableEn", "English", "Available"),
      txt("keyTaken", "keyTaken", "مشغول"),
      txt("keyTakenEn", "English", "Taken"),
      txt("footerCapacity", "footerCapacity", "سعة القاعة"),
      txt("footerCapacityEn", "English", "Hall capacity"),
      txt("footerSeats", "footerSeats", "مقعدًا"),
      txt("footerSeatsEn", "English", "seats"),
      txt("bookCta", "bookCta", "احجز مقعدك"),
      txt("bookCtaEn", "English", "Book your seat"),
    ],
  },

];

/** Build DEFAULT_CONTENT from schema. */
export const DEFAULT_CONTENT: Record<string, Record<string, string>> = (() => {
  const out: Record<string, Record<string, string>> = {};
  for (const sec of CONTENT_SCHEMA) {
    out[sec.key] = {};
    for (const f of sec.fields) out[sec.key][f.key] = f.default;
  }
  return out;
})();

router.get("/content", async (_req, res) => {
  const rows = await db.select().from(siteSettingsTable);
  const overrides: Record<string, Record<string, string>> = {};
  for (const row of rows) overrides[row.key] = row.value as Record<string, string>;
  const merged: Record<string, Record<string, string>> = {};
  for (const sec of CONTENT_SCHEMA) {
    merged[sec.key] = { ...DEFAULT_CONTENT[sec.key], ...(overrides[sec.key] ?? {}) };
  }
  res.json({ content: merged });
});

router.get("/admin/content", requireAdmin, async (_req, res) => {
  const rows = await db.select().from(siteSettingsTable);
  const overrides: Record<string, Record<string, string>> = {};
  for (const row of rows) overrides[row.key] = row.value as Record<string, string>;
  const merged: Record<string, Record<string, string>> = {};
  for (const sec of CONTENT_SCHEMA) {
    merged[sec.key] = { ...DEFAULT_CONTENT[sec.key], ...(overrides[sec.key] ?? {}) };
  }
  res.json({ schema: CONTENT_SCHEMA, defaults: DEFAULT_CONTENT, overrides, merged });
});

const upsertSchema = z.object({
  value: z.record(z.string(), z.string()),
});

const SECTION_INDEX = new Map(CONTENT_SCHEMA.map((s) => [s.key, s] as const));
const FIELD_INDEX = new Map<string, Map<string, FieldDef>>(
  CONTENT_SCHEMA.map((s) => [s.key, new Map(s.fields.map((f) => [f.key, f]))]),
);

router.put("/admin/content/:key", requireAdmin, async (req, res) => {
  const key = String(req.params.key ?? "");
  const section = SECTION_INDEX.get(key);
  if (!section) {
    res.status(400).json({ error: "قسم غير معروف" });
    return;
  }
  const parsed = upsertSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "قيمة غير صالحة" });
    return;
  }
  const fields = FIELD_INDEX.get(key)!;
  const cleaned: Record<string, string> = {};
  const unknownKeys: string[] = [];
  const isSafeUrlOrPath = (v: string): boolean => {
    if (v === "") return true;
    if (v.startsWith("/")) return true; // relative path (uploads, public assets)
    if (/^(mailto:|tel:)/i.test(v)) return true;
    try {
      const u = new URL(v);
      return u.protocol === "http:" || u.protocol === "https:";
    } catch {
      return false;
    }
  };
  for (const [fk, fv] of Object.entries(parsed.data.value)) {
    const def = fields.get(fk);
    if (!def) {
      unknownKeys.push(fk);
      continue;
    }
    if (typeof fv !== "string") {
      res.status(400).json({ error: `قيمة الحقل ${fk} يجب أن تكون نصّاً` });
      return;
    }
    if (fv.length > 8000) {
      res.status(400).json({ error: `حقل ${fk} يتجاوز الحدّ المسموح` });
      return;
    }
    if ((def.type === "url" || def.type === "image") && !isSafeUrlOrPath(fv)) {
      res.status(400).json({ error: `قيمة غير صالحة للحقل ${fk}` });
      return;
    }
    cleaned[fk] = fv;
  }
  if (unknownKeys.length > 0) {
    res.status(400).json({
      error: `حقول غير معروفة في القسم ${key}: ${unknownKeys.join(", ")}`,
      unknownKeys,
    });
    return;
  }
  await db
    .insert(siteSettingsTable)
    .values({ key, value: cleaned })
    .onConflictDoUpdate({
      target: siteSettingsTable.key,
      set: { value: cleaned, updatedAt: sql`now()` },
    });
  res.json({ ok: true });
});

router.delete("/admin/content/:key", requireAdmin, async (req, res) => {
  const key = String(req.params.key ?? "");
  await db
    .delete(siteSettingsTable)
    .where(sql`${siteSettingsTable.key} = ${key}`);
  res.json({ ok: true });
});

export default router;
