import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminRouter from "./admin";
import adminExtraRouter from "./adminExtra";
import applicationsRouter from "./applications";
import bookingsRouter from "./bookings";
import contentRouter from "./content";
import analyticsRouter from "./analytics";
import uploadRouter from "./upload";
import storageRouter from "./storage";
import authRouter from "./auth";
import coursesRouter from "./courses";
import worksRouter from "./works";
import dailyRouter from "./daily";
import statsRouter from "./stats";
import userUploadRouter from "./userUpload";
import membersRouter from "./members";
import numbersRouter from "./numbers";
import galleryRouter from "./gallery";
import pushRouter from "./push";
import expertsRouter from "./experts";
import programsRouter from "./programs";
import venturesRouter from "./ventures";
import successStoriesRouter from "./successStories";
import partnersRouter from "./partners";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminRouter);
router.use(adminExtraRouter);
router.use(applicationsRouter);
router.use(bookingsRouter);
router.use(contentRouter);
router.use(analyticsRouter);
router.use(uploadRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(coursesRouter);
router.use(worksRouter);
router.use(dailyRouter);
router.use(statsRouter);
router.use(userUploadRouter);
router.use(membersRouter);
router.use(numbersRouter);
router.use(galleryRouter);
router.use(pushRouter);
router.use(expertsRouter);
router.use(programsRouter);
router.use(venturesRouter);
router.use(successStoriesRouter);
router.use(partnersRouter);

export default router;
