import { Router, type IRouter } from "express";
import { adminGate } from "../lib/adminGate";
import healthRouter from "./health";
import adminRouter from "./admin";
import adminTeamRouter from "./adminTeam";
import adminExtraRouter from "./adminExtra";
import applicationsRouter from "./applications";
import contactRouter from "./contact";
import bookingsRouter from "./bookings";
import contentRouter from "./content";
import analyticsRouter from "./analytics";
import uploadRouter from "./upload";
import storageRouter from "./storage";
import authRouter from "./auth";
import coursesRouter from "./courses";
import worksRouter from "./works";
import dailyRouter from "./daily";
import blogRouter from "./blog";
import statsRouter from "./stats";
import userUploadRouter from "./userUpload";
import membersRouter from "./members";
import rosterRouter from "./roster";
import numbersRouter from "./numbers";
import galleryRouter from "./gallery";
import pushRouter from "./push";
import expertsRouter from "./experts";
import notificationsRouter from "./notifications";
import programsRouter from "./programs";
import venturesRouter from "./ventures";
import opportunitiesRouter from "./opportunities";
import courseProgressRouter from "./courseProgress";
import messagingRouter from "./messaging";
import sessionRatingsRouter from "./sessionRatings";
import gamificationRouter from "./gamification";
import perksRouter from "./perks";
import notificationPrefsRouter from "./notificationPrefs";
import successStoriesRouter from "./successStories";
import partnersRouter from "./partners";
import teamMembersRouter from "./teamMembers";
import cohortsRouter from "./cohorts";
import ventureMilestonesRouter from "./ventureMilestones";
import expertAvailabilityRouter from "./expertAvailability";
import resourcesRouter from "./resources";
import searchRouter from "./search";
import jobsRouter from "./jobs";
import newsletterRouter from "./newsletter";
import investorsRouter from "./investors";
import tasksRouter from "./tasks";
import attendanceRouter from "./attendance";
import attendanceHrRouter from "./attendanceHr";
import broadcastRouter from "./broadcast";
import adminMessagesRouter from "./adminMessages";
import adminContactRouter from "./adminContact";
import adminNotificationsRouter from "./adminNotifications";
import impactRouter from "./impact";
import attestationsRouter from "./attestations";
import trashRouter from "./trash";
import ctaRouter from "./cta";
import pagesRouter from "./pages";

const router: IRouter = Router();

// Centralized RBAC gate — enforces per-permission access on EVERY /admin/* route
// (fail-closed on unmapped segments). Runs before the routers; non-admin paths
// pass straight through. Per-route requireAdmin/requirePermission still apply as
// defense-in-depth and reuse the admin this gate already resolved.
router.use(adminGate);

router.use(healthRouter);
router.use(adminRouter);
router.use(adminTeamRouter);
router.use(adminExtraRouter);
router.use(applicationsRouter);
  router.use(contactRouter);
router.use(bookingsRouter);
router.use(contentRouter);
router.use(analyticsRouter);
router.use(uploadRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(coursesRouter);
router.use(worksRouter);
router.use(dailyRouter);
router.use(blogRouter);
router.use(statsRouter);
router.use(userUploadRouter);
router.use(membersRouter);
router.use(rosterRouter);
router.use(numbersRouter);
router.use(attestationsRouter);
router.use(galleryRouter);
router.use(pushRouter);
router.use(expertAvailabilityRouter);
router.use(expertsRouter);
router.use(notificationsRouter);
router.use(programsRouter);
router.use(venturesRouter);
router.use(opportunitiesRouter);
router.use(courseProgressRouter);
router.use(messagingRouter);
router.use(sessionRatingsRouter);
router.use(gamificationRouter);
router.use(perksRouter);
router.use(notificationPrefsRouter);
router.use(successStoriesRouter);
router.use(partnersRouter);
router.use(teamMembersRouter);
router.use(cohortsRouter);
router.use(ventureMilestonesRouter);
router.use(resourcesRouter);
router.use(searchRouter);
router.use(jobsRouter);
router.use(newsletterRouter);
router.use(investorsRouter);
router.use(tasksRouter);
router.use(attendanceRouter);
router.use(attendanceHrRouter);
router.use(broadcastRouter);
router.use(adminMessagesRouter);
router.use(adminContactRouter);
router.use(adminNotificationsRouter);
router.use(impactRouter);
router.use(trashRouter);
router.use(ctaRouter);
router.use(pagesRouter);

export default router;
